create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password text not null,
  role text not null default 'admin',
  created_at timestamptz not null default now()
);

alter table public.admins enable row level security;

drop policy if exists "Admins can read admin records" on public.admins;
create policy "Admins can read admin records"
  on public.admins for select
  using (true);

drop policy if exists "Admins can create admin records" on public.admins;
create policy "Admins can create admin records"
  on public.admins for insert
  with check (true);

drop policy if exists "Admins can delete admin records" on public.admins;
create policy "Admins can delete admin records"
  on public.admins for delete
  using (true);